### ISSUE TITLE
allow configurable promtail container image with cephadm

### ISSUE THREAD

**Issue by ktdreyer** [red-hat-storage/cephci#1894]
Similar to https://github.com/red-hat-storage/cephci/issues/431 and https://github.com/red-hat-storage/cephci/issues/1002, we're introducing a new container image: `promtail`.

The `/usr/sbin/cephadm` script will hardcode `DEFAULT_PROMTAIL_IMAGE = 'registry.redhat.io/rhceph/rhceph-promtail-rhel9:v2.4.0'`, but we have not shipped to that location on registry.redhat.io yet.

In the meantime, before we ship this to the public registry, we need a way to override the promtail image location to use Red Hat's internal registry location:

```
registry-proxy.engineering.redhat.com/rh-osbs/promtail:2.4.0-1
```

This is probably a one-line change to cephci itself?
```diff
diff --git a/ceph/ceph_admin/bootstrap.py b/ceph/ceph_admin/bootstrap.py
index 4f09a661..f3eb52fa 100644
--- a/ceph/ceph_admin/bootstrap.py
+++ b/ceph/ceph_admin/bootstrap.py
@@ -345,6 +345,7 @@ class BootstrapMixin:
                 "prometheus",
                 "node_exporter",
                 "alertmanager",
+                "promtail",
             ]
 
             for image in supported_overrides:
```

... and then the Jenkins jobs need updates to use this CLI argument until we ship.

**Comment by psathyan** [comment]
Thanks @ktdreyer for the heads up. Yes, you have rightly pointed out what needs to be added. Thanks :) 

From testing point, we would need to add support for `loki` also. Since centralized logging is not enabled by default, I don't see any pipeline script changes in the sanity tier.

However for qunicy centralized log testing, (when the suites are ready), we would need to provide the override arguments via `--custom-config promtail_image=...`

**Comment by psathyan** [comment]
#1925 #1921 addresses this issue hence closing it.
