### ISSUE TITLE
config roll over tests are getting failed

### ISSUE THREAD

**Issue by sunilangadi2** [red-hat-storage/cephci#442]
In sanity ceph ansible roll over tests are usually getting failed
We need to fix this issue on priority.
logs:
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1617088798904/result.html
http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1617100884901/result.html

**Comment by VasishtaShastry** [comment]
@sunilangadi2
1) http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1617088798904/result.html
doesn't seems to be a ceph-ansible script issue as discussed in gchat room
2) http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-1617100884901/result.html
This failure is because of rgw services not being able to be restarted as asok file name is too long
This is not an issue with ceph-ansible, As a team we need to find a way to trim down vm names

> f280 -1 asok(0x55c6bb828000) AdminSocketConfigObs::init: failed: AdminSocket::bind_and_listen: The UNIX domain socket path /var/run/ceph/ceph-client.rgw.ceph-sanity-containerized-ceph-ansible-1617100884901-node6-mon.rgw0.103.94312037791152.asok is too long! The maximum length on this system is 107\\n

**Comment by rakeshgm** [comment]
@sunilangadi2 and @VasishtaShastry any update on this.

**Comment by sunilangadi2** [comment]
Thanks @sunilkumarn417 for trimming instance node name
As of now we are not facing this issue 
logs : http://magna002.ceph.redhat.com/cephci-jenkins/cephci-run-ZJ0DAF
Hence closing this issue.
